name       : haskell-json
version    : 0.9.2
release    : 6
source     :
    - https://hackage.haskell.org/package/json-0.9.2/json-0.9.2.tar.gz : e6bb16fa791cc3833ae7b459b7e7885c1c2b11b0d294b7e095287c54fa73738e
license    : BSD-3-Clause
component  : programming.haskell
summary    : This library provides a parser and pretty printer for converting between Haskell values and JSON.
description: |
    This library provides a parser and pretty printer for converting between Haskell values and JSON.
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-parsec
    - haskell-syb
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
