name       : haskell-json
version    : 0.9.1
release    : 2
source     :
    - https://hackage.haskell.org/package/json-0.9.1/json-0.9.1.tar.gz : 96b57e4d167e45dc80aeff872a922ae9cdb953a1ded29ebbb51019b68f0085a2
license    : BSD-3-Clause
component  : programming
summary    : This library provides a parser and pretty printer for converting between
    Haskell values and JSON.
description: |
    This library provides a parser and pretty printer for converting between Haskell values and JSON.
builddeps  :
    - ghc
    - haskell-parsec
    - haskell-syb
setup      : |
    sudo ghc-pkg recache
    ghc -threaded Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 json-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/json-$version.conf
    rm -f $installdir/usr/lib64/$GHCV/json-$version/*.a
