name       : haskell-json
version    : 0.9.1
release    : 4
source     :
    - https://hackage.haskell.org/package/json-0.9.1/json-0.9.1.tar.gz : 96b57e4d167e45dc80aeff872a922ae9cdb953a1ded29ebbb51019b68f0085a2
license    : BSD-3-Clause
component  : programming.haskell
summary    : This library provides a parser and pretty printer for converting between
    Haskell values and JSON.
description: |
    This library provides a parser and pretty printer for converting between Haskell values and JSON.
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-parsec
    - haskell-syb
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
