name       : haskell-json
version    : '0.10'
release    : 7
source     :
    - https://hackage.haskell.org/package/json-0.10/json-0.10.tar.gz : 0c046a3c03c9332816d3c9e50319b1d1eb3c2c1baba1123a7650d047b26856ba
license    : BSD-3-Clause
component  : programming.haskell
summary    : This library provides a parser and pretty printer for converting between Haskell values and JSON.
description: |
    This library provides a parser and pretty printer for converting between Haskell values and JSON.
builddeps  :
    - haskell-cabal-install
    - haskell-syb-devel
rundeps    :
    - devel:
        - haskell-syb-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
